version: "3"
services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        ports:
            - "3001:3001"
        volumes:
            - ./server:/app